version: '3'

services:
  app:
    image: openhab/openhab-cloud:latest
    build:
      context: ../..
    volumes:
    - ./config.json.template:/opt/openhabcloud/config.json.template
    depends_on:
    - mongodb
    - redis
    restart: always
    environment:
    - DOMAIN_NAME
    - EXPRESS_KEY
    ports:
      - "80:3000"  # Expose the internal port 3000 as 80 on the host

  mongodb:
    image: mongo:4
    volumes:
    - mongo-data:/data/db
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB default port 27017

  redis:
    image: bitnami/redis:latest
    environment:
    - REDIS_PASSWORD=123_openHAB
    restart: always
    ports:
      - "6379:6379"  # Expose Redis default port 6379

volumes:
  mongo-data:
  traefik-data:
